### ISSUE TITLE
Issues with buttons on IE

### ISSUE THREAD

**Issue by eugenemc** [CoderDojo/Zen#11]
The buttons are not rendering correctly or submitting on IE

This screen shot is IE7:
http://browsershots.org/screenshots/97d5149b9b3e7d6fafe2748f173ebad4

I have also tested on IE9 in both standard and compatibility mode.

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
