### ISSUE TITLE
Alternate Ticket registrations

### ISSUE THREAD

**Issue by samkhawse** [CoderDojo/Zen#17]
Hi,
   I am the coordinator of CoderDojo Des Moines.

We want to use http://Tikly.co for ticket registration, instead on Eventbright. Tikly is a rising startup providing registrations and is our sponsor.

The Tikly team has created an iframe widget for us to embed in the CoderDojo page. unfortunately I don't have any PHP skills (Java programmer) and don't know how to change the CoderDojo Zen framework.

The code to embed the iframe is:
```
            <div style="width:550px; height:800px; text-align:left; margin-left: 37px;">
                 <iframe src="https://tikly.co/buy.php?iframe&event=589" style="width: 510px; height: 800px;" frameborder="0" onload="scroll(0,0);"></iframe>  
            </div>
```

Please help!

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
