### ISSUE TITLE
sample data for demo and testing

### ISSUE THREAD

**Issue by emeraldjava** [CoderDojo/Zen#24]
Hi,
I've just pulled down the code and created the schema. I would be good if there was a small sql script which would populate the schema with demo data. The script might create two or three users and a couple of dojo's. This would allow the developer or tester to get up and running more quickly.
Regards,
Paul

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
