### ISSUE TITLE
Filter on term 'CoderDojo' in Dojo name field

### ISSUE THREAD

**Issue by Whelton** [CoderDojo/Zen#3]
People name their Dojo, 'CoderDojo XYZ', but its implicit as they are on the Zen and looking at the Dojo list, it is a Dojo. 

I have it noted asking them not to use the term 'CoderDojo' next to the dojo name field on the dojo/create and dojo/edit views, but we need to add a filter to the validation class to stop this and throwback an error or something.

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
