### ISSUE TITLE
Better URL for Dojo listings

### ISSUE THREAD

**Issue by Whelton** [CoderDojo/Zen#4]
Change from or add ability to have URL format of "http://zen.coderdojo.com/dojo/{id}", to "http://zen.coderdojo.com/dojo/{country}/{city}/{name}/", or pending on the country "http://zen.coderdojo.com/dojo/{country}/{state}/{city}/{name}" for Dojo listings. Short URLs would be pretty rad also.

Example CoderDojo Tokyo's listing is currently "http://zen.coderdojo.com/dojo/57", change that to "http://zen.coderdojo.com/dojo/japan/tokyo"

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
