### ISSUE TITLE
Improve country and location options on Dojo listing

### ISSUE THREAD

**Issue by Whelton** [CoderDojo/Zen#6]
Currently when creating a Dojo, a user chooses a country and then enters a location for the Dojo. In the long run, I see this presenting issues, especially with searching for and categorising Dojos.

Narrow this down by getting a user to select a state/county and then a city or town.

**Comment by tangentfairy** [comment]
This repository is now just for historical reference only.

The new zen.coderdojo.com can be found at https://github.com/CoderDojo/community-platform/
